version: "3"
services:
  postgres_db:
    image: postgres
    container_name: eng2-project
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=eng2-project